const TOPICS = [
  { slug: 'c', name: 'C' },
  { slug: 'cpp', name: 'C++' },
  { slug: 'csharp', name: 'C#' },
  { slug: 'java', name: 'Java' },
  { slug: 'kotlin', name: 'Kotlin' },
  { slug: 'scala', name: 'Scala' },
  { slug: 'groovy', name: 'Groovy' },
  { slug: 'python', name: 'Python' },
  { slug: 'ruby', name: 'Ruby' },
  { slug: 'perl', name: 'Perl' },
  { slug: 'php', name: 'PHP' },
  { slug: 'javascript', name: 'JavaScript' },
  { slug: 'typescript', name: 'TypeScript' },
  { slug: 'dart', name: 'Dart' },
  { slug: 'go', name: 'Go' },
  { slug: 'rust', name: 'Rust' },
  { slug: 'swift', name: 'Swift' },
  { slug: 'objective-c', name: 'Objective-C' },
  { slug: 'haskell', name: 'Haskell' },
  { slug: 'elixir', name: 'Elixir' },
  { slug: 'erlang', name: 'Erlang' },
  { slug: 'clojure', name: 'Clojure' },
  { slug: 'r', name: 'R' },
  { slug: 'matlab', name: 'MATLAB' },
  { slug: 'julia', name: 'Julia' },
  { slug: 'fortran', name: 'Fortran' },
  { slug: 'cobol', name: 'COBOL' },
  { slug: 'fsharp', name: 'F#' },
  { slug: 'nim', name: 'Nim' },
  { slug: 'zig', name: 'Zig' },
  { slug: 'ocaml', name: 'OCaml' },
  { slug: 'lua', name: 'Lua' },
  { slug: 'powershell', name: 'PowerShell' },
  { slug: 'bash', name: 'Bash' },
];

export { TOPICS };
